site_name: Spatial Omics Live Review
site_url: https://marta-seq.github.io/solr/ # <--- ADD OR UPDATE THIS LINE
site_description: A live review and exploration of Spatial Omics literature and data.

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
  palette:
    - scheme: default
      primary: 'indigo'
      accent: 'light blue'

nav:
  - Home: index.md
  - Book:
      - Introduction: book/index.md  # Your book's introduction
      - Chapter 1: book/chapter1.md
      - Chapter 2: book/chapter2.md
      - Chapter 3: book/chapter3.md
      - References: book/references.md

      # You can nest further for sections within chapters:
      # - Chapter 4:
      #   - Section A: book/chapter4-sectionA.md
      #   - Section B: book/chapter4-sectionB.md
  - Spatial Omics Datasets: datasets/index.md
  - Spatial Omics Methods: methods/index.md
  - Spatial Omics Applications: applications/index.md