site_name: Spatial Omics Live Review
site_url: https://marta-seq.github.io/solr/ # <--- ADD OR UPDATE THIS LINE
site_description: A live review and exploration of Spatial Omics literature and data.

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
  palette:
    - scheme: default
      primary: 'indigo'
      accent: 'light blue'

nav:
  - Home: index.md
  - Book: book/index.md
  - Spatial Omics Datasets: datasets/index.md
  - Spatial Omics Methods: methods/index.md
  - Spatial Omics Applications: applications/index.md