"""
data_fetch_agent.py (data desk)
For one paper (method or application - anything that reaches this point):
reads the data-availability text, asks the LLM which datasets are mentioned
and whether each was generated by this paper or reused from elsewhere,
resolves the "reused" case's origin paper via the same reference-list-first
resolver the methods desk uses, matches against the existing DB or creates a
new D_* entry (+ a stub Application paper if the origin paper doesn't exist
yet), and links the paper's own DataID field. Single pass - never recursive,
never queues anything for further processing.

Nothing here writes to the master Excel - everything goes through
common.staging.append_candidate().
"""

import re

from ...common import config, staging
from ...common.doi_utils import normalize_doi
from ...common.llm_client import call_llm_json, LLMError, LLMExhaustedError
from ...common.paper_fetcher import fetch_paper, get_agent_text, is_probably_real_content
from ...common.reference_list_parser import parse_reference_list
from ...common.reference_resolver import resolve_citation, is_confident

SYSTEM_PROMPT = """You are a careful research assistant extracting factual information from a \
scientific paper's data availability statement (or, if that wasn't available, the paper's full \
text). Identify every distinct dataset mentioned - whether newly generated by this paper or \
reused from a prior publication or public repository.

Return ONLY a JSON array, nothing else, no markdown fences. Each element:
{
  "relationship": "self_generated" | "reused_external" | "unclear",
  "accession": "repository accession number (e.g. GEO GSExxxxx, ArrayExpress E-MTAB-xxxx), or \
empty string if none given",
  "data_doi": "a DOI printed for the dataset ITSELF (common for Zenodo/Dryad/figshare, rare for \
GEO/ArrayExpress), or empty string",
  "access_link": "a URL where the data can be accessed, or empty string",
  "technique": "the spatial technique used for this dataset if stated (e.g. 'IMC', 'CODEX', \
'MERFISH', 'Visium', 'Xenium', 'seqFISH'), or empty string if not stated",
  "modality": "spatial_proteomics" | "spatial_transcriptomics" | "spatial_multi" | "unknown",
  "origin_citation_marker": "ONLY if relationship is reused_external and there is a numbered \
reference (e.g. '15') pointing to the paper that originally generated this data - the number as \
it appears. Empty string otherwise.",
  "origin_citation_text": "ONLY if relationship is reused_external and origin_citation_marker is \
empty - an author-year citation for the original paper (e.g. 'Smith et al., 2020'). Empty \
string otherwise."
}
Do not include preprocessing intermediate files, code repositories, or supplementary figures -
only actual experimental datasets. If nothing is mentioned, return an empty JSON array: []
"""


def _build_user_prompt(paper_entry_id: str, text: str) -> str:
    return f"Data availability text (paper {paper_entry_id}):\n\n{text}"


def _sheet_for_modality(modality: str) -> str:
    """As of the method_pub/AP_pub/data schema there's only one dataset
    sheet - kept as a function (rather than inlining the literal) since
    _id_prefix_for_modality still needs a per-modality answer for ID naming,
    and it's clearer to keep "which sheet" and "which ID prefix" as two
    separate questions even though the sheet answer is now constant."""
    return "data"


def _id_prefix_for_modality(modality: str) -> str:
    m = (modality or "").lower()
    if "multi" in m:
        return "D_MULTI"
    if "proteomic" in m:
        return "D_SP"
    if "transcriptomic" in m:
        return "D_ST"
    return "D_MULTI"  # safest catch-all when genuinely unclear


def _sheet_for_paper_entry(entry_id: str) -> str:
    """Infers which pub sheet a paper entry_id lives in. Application papers
    (including stubs this same agent creates) use the "AP_..." ID prefix;
    everything else is a method_pub entry. Needed because process_paper()
    is shared by both method and application papers (per its own docstring),
    but method_pub/AP_pub are now separate sheets with different columns."""
    return "AP_pub" if str(entry_id).upper().startswith("AP") else "method_pub"


def _data_used_field_for_sheet(sheet: str) -> str:
    """method_pub tracks datasets used via 'DataID (data_used_in_the_paper)';
    AP_pub's equivalent native column is 'Associated data' - reuse that
    instead of creating a stray DataID column on AP_pub rows."""
    return "Associated data" if sheet == "AP_pub" else "DataID (data_used_in_the_paper)"


def _technique_slug(technique: str) -> str:
    """Best-effort ID component from the LLM's free-text technique guess.
    Won't always match your existing hand-picked abbreviation style (e.g.
    'D_ST_COSM16' for CosMx) - flagged as auto-generated via REVIEW_STATUS,
    so treat generated IDs as a starting point to rename on merge, not final."""
    if not technique:
        return "NEW"
    slug = re.sub(r"[^A-Za-z0-9]", "", technique).upper()
    return slug[:10] if slug else "NEW"


def _find_by_accession(datasets_df, accession: str):
    if not accession or "data_accession_number" not in datasets_df.columns:
        return None
    col = datasets_df["data_accession_number"].astype(str).str.strip()
    matches = datasets_df[col == accession.strip()]
    if not matches.empty:
        return matches.iloc[0]["entry_id"]
    return None


def _append_id_list(existing, new_id: str, sep: str = "; ") -> str:
    existing = "" if existing is None else str(existing).strip()
    if existing in ("", "nan", "NA"):
        return new_id
    ids = [x.strip() for x in re.split(r"[;,]", existing) if x.strip()]
    if new_id not in ids:
        ids.append(new_id)
    return sep.join(ids)


def _lookup_field(df, entry_id: str, column: str):
    row = df.loc[df["entry_id"] == entry_id, column]
    return row.iloc[0] if not row.empty else ""


def _empty_stats(skip_reason: str, llm_exhausted: bool = False) -> dict:
    """Consistent return shape at every early-exit point. skip_reason is
    ALWAYS a non-empty string here (the LLM was never called) - callers
    should show it directly rather than leaving people to infer whether
    0 results means 'skipped' or 'called and found nothing'.
    llm_exhausted is True ONLY when the whole provider/model chain failed
    (LLMExhaustedError) - run_pipeline.py checks this to stop a run early
    instead of repeating the same doomed wait on every remaining paper."""
    return {"linked_ids": [], "total_encountered": 0, "total_resolved": 0,
            "skip_reason": skip_reason, "llm_exhausted": llm_exhausted}


def process_paper(db, paper_entry: dict, fetched: dict = None, reference_map: dict = None) -> dict:
    """
    paper_entry: {"entry_id": ..., "doi": ...} (depth is irrelevant here - not recursive)
    fetched/reference_map: pass these in if the orchestrator already fetched
    this paper for the methods desk pass, to avoid re-fetching/re-parsing.

    Returns {"linked_ids": [...], "total_encountered": N, "total_resolved": M,
    "skip_reason": str or None}. skip_reason is None ONLY when the LLM was
    genuinely called - always check this field rather than inferring from a
    0 count. linked_ids is every D_* entry_id linked or created - nothing
    here feeds back into any queue (this track is never recursive).
    """
    entry_id = paper_entry["entry_id"]
    doi = paper_entry["doi"]
    data_ids_linked = []

    if fetched is None:
        fetched = fetch_paper(doi)

    text, _source = get_agent_text(fetched, "data_availability")
    if not text:
        text = fetched.get("text", "")  # many papers don't have a clean heading for this
    if not text:
        staging.append_candidate(
            action="update_field", sheet=_sheet_for_paper_entry(entry_id), entry_id=entry_id, fields={},
            source_paper_entry_id=entry_id, curation_agent="data_fetch_agent",
            curation_model="none", confidence=0.0,
            notes=f"No text available to extract data availability from (fetch source: {fetched['source']}).",
        )
        return _empty_stats(f"no text could be fetched (fetch source: {fetched['source']})")

    if not is_probably_real_content(text):
        staging.append_candidate(
            action="update_field", sheet=_sheet_for_paper_entry(entry_id), entry_id=entry_id, fields={},
            source_paper_entry_id=entry_id, curation_agent="data_fetch_agent",
            curation_model="none", confidence=0.0,
            notes=f"Extracted text (source: {_source}) failed the content quality check - "
                  f"looks like website navigation/boilerplate rather than real article text. "
                  f"Skipped the LLM call to avoid wasting budget on unreliable input.",
        )
        return _empty_stats(f"text (source: {_source}) failed the content-quality check "
                             f"(looked like navigation/boilerplate, not real article text)")

    if config.REQUIRE_ISOLATED_SECTION and _source != "section:data_availability":
        staging.append_candidate(
            action="update_field", sheet=_sheet_for_paper_entry(entry_id), entry_id=entry_id, fields={},
            source_paper_entry_id=entry_id, curation_agent="data_fetch_agent",
            curation_model="none", confidence=0.0,
            notes=f"Could not cleanly isolate the data-availability section (got '{_source}' "
                  f"instead) - skipped the LLM call rather than spend a query on unfocused/"
                  f"low-confidence text.",
        )
        return _empty_stats(f"could not cleanly isolate the data-availability section "
                             f"(got '{_source}' instead of 'section:data_availability') - "
                             f"REQUIRE_ISOLATED_SECTION blocked the LLM call")

    if reference_map is None:
        references_text, _ = get_agent_text(fetched, "references")
        reference_map = parse_reference_list(references_text) if references_text else {}

    try:
        extracted, model_used = call_llm_json(SYSTEM_PROMPT, _build_user_prompt(entry_id, text))
    except LLMError as e:
        staging.append_candidate(
            action="update_field", sheet=_sheet_for_paper_entry(entry_id), entry_id=entry_id, fields={},
            source_paper_entry_id=entry_id, curation_agent="data_fetch_agent",
            curation_model="none", confidence=0.0, notes=f"LLM extraction failed: {e}",
        )
        return _empty_stats(f"LLM WAS called but every provider/model failed: {e}",
                             llm_exhausted=isinstance(e, LLMExhaustedError))

    if not isinstance(extracted, list):
        extracted = []

    for item in extracted:
        item = item or {}
        relationship = (item.get("relationship") or "unclear").strip().lower()
        accession = (item.get("accession") or "").strip()
        data_doi = normalize_doi(item.get("data_doi", ""))
        access_link = (item.get("access_link") or "").strip()
        technique = (item.get("technique") or "").strip()
        modality = (item.get("modality") or "").strip()
        origin_marker = (item.get("origin_citation_marker") or "").strip()
        origin_text = (item.get("origin_citation_text") or "").strip()

        if not accession and not data_doi and not access_link:
            continue  # nothing usable in this mention

        # --- matching against existing DB first ---
        existing_id = db.doi_index.lookup(data_doi) if data_doi else None
        if existing_id is None and accession:
            existing_id = _find_by_accession(db.datasets, accession)

        if existing_id:
            data_ids_linked.append(existing_id)
            continue

        # --- not found: resolve who produced this data before creating ---
        paper_doi_field, paper_entry_id_field = "", ""
        origin_confidence = None
        origin_note = ""

        if relationship == "self_generated":
            paper_doi_field, paper_entry_id_field = doi, entry_id
            origin_confidence = 1.0

        elif relationship == "reused_external":
            resolved = resolve_citation(origin_marker, origin_text, reference_map)
            if is_confident(resolved) and resolved["resolved_doi"]:
                origin_confidence = resolved["confidence"]
                origin_doi = resolved["resolved_doi"]
                existing_paper_id = db.doi_index.lookup(origin_doi)
                if existing_paper_id:
                    paper_doi_field, paper_entry_id_field = origin_doi, existing_paper_id
                else:
                    stub_id = db.id_allocator.next_id("AP")
                    staging.append_candidate(
                        action="create_entry", sheet="AP_pub", entry_id=stub_id,
                        fields={
                            "DOI": origin_doi,
                            "category": "Application",
                            "REVIEW_STATUS": config.REVIEW_STATUS_NEEDS_REVIEW,
                        },
                        source_paper_entry_id=entry_id, curation_agent="data_fetch_agent",
                        curation_model=model_used, confidence=resolved["confidence"],
                        notes=f"Auto-created stub: original source paper for data reused in {entry_id}.",
                    )
                    db.doi_index.add(origin_doi, stub_id)
                    paper_doi_field, paper_entry_id_field = origin_doi, stub_id
            else:
                origin_note = (" Original paper for this reused dataset could not be confidently "
                               "resolved - paper_DOI left blank for manual linking.")
        else:
            origin_note = " Relationship to source paper unclear - paper_DOI left blank for manual linking."

        sheet = _sheet_for_modality(modality)
        prefix = f"{_id_prefix_for_modality(modality)}_{_technique_slug(technique)}"
        new_id = db.id_allocator.next_id(prefix)

        confident_enough = (relationship == "self_generated") or (
            origin_confidence is not None and origin_confidence >= 0.55
        )
        review_status = config.REVIEW_STATUS_AUTO if confident_enough else config.REVIEW_STATUS_NEEDS_REVIEW

        staging.append_candidate(
            action="create_entry", sheet=sheet, entry_id=new_id,
            fields={
                "data_DOI": data_doi,
                "data_accession_number": accession,
                "data_acess_link": access_link,
                "paper_DOI": paper_doi_field,
                "paper_ENTRY_ID": paper_entry_id_field,
                "spatial_data_category": modality,
                "spatial_data_method": technique,
                "REVIEW_STATUS": review_status,
            },
            source_paper_entry_id=entry_id, curation_agent="data_fetch_agent",
            curation_model=model_used, confidence=origin_confidence,
            notes=f"Extracted from data-availability text in {entry_id} "
                  f"(relationship: {relationship}).{origin_note}",
        )

        if data_doi:
            db.doi_index.add(data_doi, new_id)
        data_ids_linked.append(new_id)

    if data_ids_linked:
        paper_sheet = _sheet_for_paper_entry(entry_id)
        data_used_field = _data_used_field_for_sheet(paper_sheet)
        existing_value = _lookup_field(db.methods, entry_id, data_used_field)
        updated_value = existing_value
        for did in data_ids_linked:
            updated_value = _append_id_list(updated_value, did)

        staging.append_candidate(
            action="update_field", sheet=paper_sheet, entry_id=entry_id,
            fields={data_used_field: updated_value},
            source_paper_entry_id=entry_id, curation_agent="data_fetch_agent",
            curation_model=model_used, confidence=None,
            notes="Appended newly-found/linked dataset IDs.",
        )

    return {
        "linked_ids": data_ids_linked,
        "total_encountered": len(extracted),
        "total_resolved": len(data_ids_linked),
        "skip_reason": None,
    }
